project:
  type: book

book:
  title: "Curso de Geoanálisis"
  subtitle: "Para la mejora en la implementación de Políticas Públicas"
  author:
    - name: Denis Berroeta González
      url: https://cit.uai.cl/denis-berroeta/
      affiliation: Centro de Inteligencia Territorial
      affiliation-url: https://cit.uai.cl
      email: denis.berroeta@uai.cl
  date: "2025-7-22"
  page-footer: 
    left: "Copyright 2026, Denis Berroeta" 
  chapters:
    - index.qmd
    - geoanalisis.qmd
    - intro_r.qmd
    - variables.qmd
    - funciones.qmd
    # - tidyverse.qmd
    # - visualizaciones.qmd
    # - datos_vectores.qmd
    # - dataframes.qmd
    # - geocode.qmd
    # - datos_rasters.qmd
    # - inferencia.qmd
    # - intro_inds.qmd
    # - indicadores_territoriales.qmd
    # - construccion_inds.qmd
    # - indicadores.qmd
    # - proyecto.qmd
    # - part: "Tareas"
      # chapters:
        # - tarea_1.qmd
        # - tarea_2.qmd
    - references.qmd
  appendices:
    - recursos.qmd
    # - control_r.qmd
    # - crs.qmd
    # - john_snow.qmd
    # - quiebres.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "denis.berroeta@uai.cl"
    toc-title: "Contenidos"
    toc-depth: 3
    number-sections: true 
    number-depth: 3 
  
execute:
  warning: false
  
editor: source
always_allow_html: true



